<a href="https://colab.research.google.com/github/varshiniv-dev/internship-ai/blob/main/day07%20and%20day08.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
df = pd.read_csv("/content/ecommerce_sales_dataset.csv") #to load dataset
print(df) #to display the dataset

    Order_ID Product_Category  Price  Quantity  Customer_Rating
0       1001            Books   1894         4              3.8
1       1002      Electronics   2210         1              4.6
2       1003         Clothing    897         2              4.2
3       1004         Clothing   3890         1              2.8
4       1005      Electronics   3529         3              3.6
5       1006             Home   2228         2              4.7
6       1007             Home    697         3              4.8
7       1008             Home   2349         4              4.8
8       1009             Home   3522         4              2.5
9       1010             Home   3080         5              4.4
10      1011             Home   1981         5              3.0
11      1012      Electronics   1679         1              4.8
12      1013             Home   2130         2              4.2
13      1014             Home    733         2              2.9
14      1015         Clothing   2742         2              2.6
15      1016             Home   2703         4              5.0
16      1017      Electronics    331         5              3.1
17      1018      Electronics   3863         5              2.9
18      1019      Electronics   3464         1              3.4
19      1020         Clothing   2759         5              5.0

In [20]:
df.columns #column names

Index(['Order_ID', 'Product_Category', 'Price', 'Quantity', 'Customer_Rating'], dtype='object')

In [6]:
df.head() #to view first 5 rows

   Order_ID Product_Category  Price  Quantity  Customer_Rating
0      1001            Books   1894         4              3.8
1      1002      Electronics   2210         1              4.6
2      1003         Clothing    897         2              4.2
3      1004         Clothing   3890         1              2.8
4      1005      Electronics   3529         3              3.6

In [7]:
df.tail() #to view last 5 rows

    Order_ID Product_Category  Price  Quantity  Customer_Rating
15      1016             Home   2703         4              5.0
16      1017      Electronics    331         5              3.1
17      1018      Electronics   3863         5              2.9
18      1019      Electronics   3464         1              3.4
19      1020         Clothing   2759         5              5.0

In [8]:
df.info() #info of the whole dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          20 non-null     int64
 1   Product_Category  20 non-null     object
 2   Price             20 non-null     int64
 3   Quantity          20 non-null     int64
 4   Customer_Rating   20 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 932.0+ bytes

In [21]:
#how many total orders today?
len(df)

20

In [11]:
#how any product categories the company has?
df["Product_Category"]

0           Books
1     Electronics
2        Clothing
3        Clothing
4     Electronics
5            Home
6            Home
7            Home
8            Home
9            Home
10           Home
11    Electronics
12           Home
13           Home
14       Clothing
15           Home
16    Electronics
17    Electronics
18    Electronics
19       Clothing
Name: Product_Category, dtype: object

In [10]:
#statistics of data
df.describe()

         Order_ID        Price   Quantity  Customer_Rating
count    20.00000    20.000000  20.000000        20.000000
mean   1010.50000  2334.050000   3.050000         3.855000
std       5.91608  1077.293073   1.538112         0.889397
min    1001.00000   331.000000   1.000000         2.500000
25%    1005.75000  1840.250000   2.000000         2.975000
50%    1010.50000  2288.500000   3.000000         4.000000
75%    1015.25000  3176.000000   4.250000         4.725000
max    1020.00000  3890.000000   5.000000         5.000000

In [12]:
len(df["Product_Category"]) #length of one complete column

20

In [14]:
#cal of avg price
df["Price"].mean() #lowest product price

np.float64(2334.05)

In [15]:
df["Price"].max()  #highest product price

3890

In [16]:
df["Product_Category"].nunique() #number of categories

4

In [17]:
df["Product_Category"].unique() #category names

array(['Books', 'Electronics', 'Clothing', 'Home'], dtype=object)

In [18]:
df[df["Price"]>3000] #greater then 3000

    Order_ID Product_Category  Price  Quantity  Customer_Rating
3       1004         Clothing   3890         1              2.8
4       1005      Electronics   3529         3              3.6
8       1009             Home   3522         4              2.5
9       1010             Home   3080         5              4.4
17      1018      Electronics   3863         5              2.9
18      1019      Electronics   3464         1              3.4

In [24]:
df["Customer_Rating"].max() #highest rated products

5.0

In [27]:
df[df["Product_Category"]=="Electronics"] #electronics products only

    Order_ID Product_Category  Price  Quantity  Customer_Rating
1       1002      Electronics   2210         1              4.6
4       1005      Electronics   3529         3              3.6
11      1012      Electronics   1679         1              4.8
16      1017      Electronics    331         5              3.1
17      1018      Electronics   3863         5              2.9
18      1019      Electronics   3464         1              3.4

In [29]:
df[df["Product_Category"]=="Clothing"] #clothing products only

    Order_ID Product_Category  Price  Quantity  Customer_Rating
2       1003         Clothing    897         2              4.2
3       1004         Clothing   3890         1              2.8
14      1015         Clothing   2742         2              2.6
19      1020         Clothing   2759         5              5.0

In [25]:
df[df["Product_Category"]=="Home"] #home products only

    Order_ID Product_Category  Price  Quantity  Customer_Rating
5       1006             Home   2228         2              4.7
6       1007             Home    697         3              4.8
7       1008             Home   2349         4              4.8
8       1009             Home   3522         4              2.5
9       1010             Home   3080         5              4.4
10      1011             Home   1981         5              3.0
12      1013             Home   2130         2              4.2
13      1014             Home    733         2              2.9
15      1016             Home   2703         4              5.0

In [30]:
#nested
df[
    (df["Product_Category"]=="Electronics") &
    (df["Price"]>3000)
] #Expensive electronics

    Order_ID Product_Category  Price  Quantity  Customer_Rating
4       1005      Electronics   3529         3              3.6
17      1018      Electronics   3863         5              2.9
18      1019      Electronics   3464         1              3.4

In [34]:
df[
    (df["Product_Category"]=="Electronics") &
    (df["Customer_Rating"]>3)
] #high rated electronics

    Order_ID Product_Category  Price  Quantity  Customer_Rating
1       1002      Electronics   2210         1              4.6
4       1005      Electronics   3529         3              3.6
11      1012      Electronics   1679         1              4.8
16      1017      Electronics    331         5              3.1
18      1019      Electronics   3464         1              3.4

In [35]:
df.sort_values("Price") #sorting by ascending order

    Order_ID Product_Category  Price  Quantity  Customer_Rating
16      1017      Electronics    331         5              3.1
6       1007             Home    697         3              4.8
13      1014             Home    733         2              2.9
2       1003         Clothing    897         2              4.2
11      1012      Electronics   1679         1              4.8
0       1001            Books   1894         4              3.8
10      1011             Home   1981         5              3.0
12      1013             Home   2130         2              4.2
1       1002      Electronics   2210         1              4.6
5       1006             Home   2228         2              4.7
7       1008             Home   2349         4              4.8
15      1016             Home   2703         4              5.0
14      1015         Clothing   2742         2              2.6
19      1020         Clothing   2759         5              5.0
9       1010             Home   3080         5              4.4
18      1019      Electronics   3464         1              3.4
8       1009             Home   3522         4              2.5
4       1005      Electronics   3529         3              3.6
17      1018      Electronics   3863         5              2.9
3       1004         Clothing   3890         1              2.8

In [36]:
df.sort_values(
 "Price",
 ascending=False
)
#sorting by decending order

    Order_ID Product_Category  Price  Quantity  Customer_Rating
3       1004         Clothing   3890         1              2.8
17      1018      Electronics   3863         5              2.9
4       1005      Electronics   3529         3              3.6
8       1009             Home   3522         4              2.5
18      1019      Electronics   3464         1              3.4
9       1010             Home   3080         5              4.4
19      1020         Clothing   2759         5              5.0
14      1015         Clothing   2742         2              2.6
15      1016             Home   2703         4              5.0
7       1008             Home   2349         4              4.8
5       1006             Home   2228         2              4.7
1       1002      Electronics   2210         1              4.6
12      1013             Home   2130         2              4.2
10      1011             Home   1981         5              3.0
0       1001            Books   1894         4              3.8
11      1012      Electronics   1679         1              4.8
2       1003         Clothing    897         2              4.2
13      1014             Home    733         2              2.9
6       1007             Home    697         3              4.8
16      1017      Electronics    331         5              3.1

In [37]:
df["Product_Category"].value_counts()
#To count the total values of the category

Product_Category
Home           9
Electronics    6
Clothing       4
Books          1
Name: count, dtype: int64

In [42]:
df["Total_Sales"] = (
 df["Price"] * df["Quantity"]
)
print(df["Total_Sales"])

0      7576
1      2210
2      1794
3      3890
4     10587
5      4456
6      2091
7      9396
8     14088
9     15400
10     9905
11     1679
12     4260
13     1466
14     5484
15    10812
16     1655
17    19315
18     3464
19    13795
Name: Total_Sales, dtype: int64